apiVersion: v1
kind: Namespace
metadata:
    name: homeassistant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: homeassistant
    namespace: homeassistant
spec:
    interval: 1h
    url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
  values:
    env:
      - name: TZ
        value: Europe/Berlin
    ingress:
      enabled: true
      hosts:
        - host: homeassistant.luehr.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.0.0.0/8
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn-retain
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          hosts:
            - host: ha-codeserver.luehr.dev
              paths:
                - path: /
                  pathType: ImplementationSpecific
