apiVersion: v1
kind: Namespace
metadata:
  name: navidrome
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-media-nfs
spec:
  storageClassName: teanau
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.239
    path: /media
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-media
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: navidrome-media-nfs
  storageClassName: teanau
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-marc
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome-marc
  namespace: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000 
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 4533
          env:
            # Add your overrides here
            # - name: ND_LOGLEVEL
            #   value: debug
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media
              mountPath: /music
              subPath: music
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-marc
        - name: media
          persistentVolumeClaim:
            claimName: navidrome-media
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: navidrome
spec:
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: navidrome
spec:
  rules:
    - host: navidrome.luehr.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 4533
