apiVersion: v1
kind: Namespace
metadata:
    name: nextcloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 1h
    url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    chart:
        spec:
            chart: nextcloud
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: nextcloud
            version: 6.6.10
    interval: 1m0s
    timeout: 15m
    values:
        replicaCount: 1
        nextcloud:
            host: nextcloud.luehr.dev
            existingSecret:
                enabled: true
                secretName: nextcloud-admin
                usernameKey: username
                passwordKey: password
        ingress:
            enabled: true
        phpClientHttpsFix:
            enabled: true
            protocol: https
        externalDatabase:
            enabled: true
            type: mysql
            existingSecret:
                enabled: true
                secretName: nextcloud-db
                usernameKey: username
                passwordKey: mariadb-password
                databaseKey: database
        mariadb:
            enabled: true
            auth:
                database: nextcloud
                username: nextcloud
                existingSecret: nextcloud-db
            primary:
                persistence:
                    enabled: true
                    storageClass: longhorn
                    size: 8Gi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 600Gi
