apiVersion: v1
kind: Namespace
metadata:
    name: nextcloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 1h
    url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    chart:
        spec:
            chart: nextcloud
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: nextcloud
            version: 6.6.10
    interval: 1m0s
    values:
        replicaCount: 1
        nextcloud:
            host: nextcloud.luehr.dev
            existingSecret:
                enabled: true
                secretName: nextcloud-admin
                usernameKey: username
                passwordKey: password
        ingress:
            enabled: true
        phpClientHttpsFix:
            enabled: true
            protocol: https
        externalDatabase:
            enabled: true
            type: mysql
            existingSecret:
                enabled: true
                secretName: nextcloud-db
                usernameKey: username
                passwordKey: mariadb-password
                databaseKey: database
        mariadb:
            enabled: true
            auth:
                database: nextcloud
                username: nextcloud
                existingSecret: nextcloud-db
            primary:
                persistence:
                    enabled: true
                    storageClass: longhorn
                    size: 8Gi
        persistence:
            enabled: true
            storageClass: longhorn
            size: 600Gi
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:nWz8tVsTIxSU,iv:+QdKK5UMKh8UYOEZuha7C6PcxgXHx3g9JFC9DRhv4F0=,tag:wWgIFKypyHAofNn+FOqruQ==,type:str]
    username: ENC[AES256_GCM,data:z4X17CyCIKPK,iv:Jt1GYRzRCjHSwqYwjd1uAVCtKEMLPZlqYrCClDs0pZY=,tag:RU5fpisZJpxQiaqe5fuw8g==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:y5XQSwEiozVmjdsu2z0cJ4hSBlPNY/np4kp3aOPR,iv:tRzxy6bt0tNM1o/E4wqc0Bz83ezD7/tPnoquFXQSl2U=,tag:EYqF/uTKJAb2CGPOL7GHaQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:ObthgJhC1SYZ3t34E9gA5k5CF/0F1XJckw0ncrem,iv:78A4Q5lmwi4IT/VxOFMCiOGBXZ1Qcuik5eEN5oCBZYs=,tag:U7eY1fzczwXV9ADaAHT0TA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:0A8xF77n+1ELa4tlIxf28bDliWg31WYyN/k9QrE+,iv:zIBPX9JjInsHOL5KMznDt2r7OXqctwnZh+qWToqvgUQ=,tag:7OkqSf2oaCiej/MMmHLzGg==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZnFzTC8xVUF4ZDV3U3VD
            bWpxOHF4TTB6NWZMcUZsaFhEWGY3QWJuZkNVCnRaU2dXSDlTUncwcDFTWmI5QkRr
            dnV1V0NvUmthdkZDQmlwaTNXdHVOUWcKLS0tIFdQMmxGYisvY0h3Wm5NbmNjSHZz
            NzRlZjNNekdGQW5DSHZ6YVNTaWp0RGcKm3dq7apFAj+OzC0ELaTEjBBhnSoNkHHu
            O5zH8FJqrLkPRo6xIm/4I+xO0dS8xmAFAT542rao0Vfzj2BkvbzDMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T19:20:54Z"
    mac: ENC[AES256_GCM,data:qfd0nY4Z+npK//oc7f21Kh6Z2GgtJZautfWgFfe16cypU1kGR4G1CIvqNpF4t4jrsttRfp2v8rKz7XQjNtX9+CVesyxM4+z4ATEJLWGjhprDRKA/sk3eDFeV39FSiPh3/afpNxh4yEFFTpIc2/nRbdPT5F4rc9kOE7BvX+8gUwM=,iv:Oj0W4QrZHukiNruE2IdfeiBbcDzFyuqlo15K9Y5iPbw=,tag:HK/krHlDlW1ho7/KrK9i+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xcGc8Rg=,iv:N6xCze4D0m/i/PJLZ57ZiWxRpCd2Lp6g6qf3U+fEw0M=,tag:5pGouSJfxNtfxyietXuwew==,type:str]
    password: ENC[AES256_GCM,data:nndrW2o6np3WmXQS/uZct7ujGHmO4wDmOkEK9nFM,iv:6opy78+RYs7CHWfySoCCcgh6mTmFnJVHj0l4Je8ki/k=,tag:5dR6eiAxaAY5uTwmMvZcJw==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZnFzTC8xVUF4ZDV3U3VD
            bWpxOHF4TTB6NWZMcUZsaFhEWGY3QWJuZkNVCnRaU2dXSDlTUncwcDFTWmI5QkRr
            dnV1V0NvUmthdkZDQmlwaTNXdHVOUWcKLS0tIFdQMmxGYisvY0h3Wm5NbmNjSHZz
            NzRlZjNNekdGQW5DSHZ6YVNTaWp0RGcKm3dq7apFAj+OzC0ELaTEjBBhnSoNkHHu
            O5zH8FJqrLkPRo6xIm/4I+xO0dS8xmAFAT542rao0Vfzj2BkvbzDMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T19:20:54Z"
    mac: ENC[AES256_GCM,data:qfd0nY4Z+npK//oc7f21Kh6Z2GgtJZautfWgFfe16cypU1kGR4G1CIvqNpF4t4jrsttRfp2v8rKz7XQjNtX9+CVesyxM4+z4ATEJLWGjhprDRKA/sk3eDFeV39FSiPh3/afpNxh4yEFFTpIc2/nRbdPT5F4rc9kOE7BvX+8gUwM=,iv:Oj0W4QrZHukiNruE2IdfeiBbcDzFyuqlo15K9Y5iPbw=,tag:HK/krHlDlW1ho7/KrK9i+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
