apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:NELHiNcs9oYK,iv:cqBlfHBgrdKUlr46jgcsGoB46N47tde4kdzkTp40cTY=,tag:cnpCevUh5R8pt8ND9pIjuA==,type:str]
    username: ENC[AES256_GCM,data:tPCcsjjfcGe3,iv:pOemFqOklB4WyDN/o2HHXHfxkWzRPMa5/JUHQvQ3+eg=,tag:ox3kmitCS5apaw+oFARNEg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:SiHDvJtW+2mVqbIRcXVpwnQl8AV5n68i9FZHuP75,iv:OJMyYajd7KpVlA47/9J0DZpat4e4NM3DSzsCclJ60uE=,tag:l9UBDR7xDsWlexobfbU3pw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:Jdd/XnT/mUDtg+uGnz0cPrJU5sssEc+I0qL96aTU,iv:ZHqiLB8BYtRsv/5CUbUSsvOWVegRyiWz7xaB4eJA0h0=,tag:oLDQw+UxkRsBdk8MowZXjg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:VIqa0/vBhWkFj1RToMsH63f1h2Lg3XAA/k4V1xKb,iv:avBIfzH06XhaJDCDuEcwe5Ymn6HJQ3p2vBJ9a2goSoI=,tag:V/Y86gO0fAExC062SQlKkg==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeW9UWW51YThuWWRHRTVs
            ZXF4WDl4YTdvT1crNW15K3U0ZWRqOUNITUZnCjVlQ21ETVpLeFp0SmhSSHMrL1Zl
            eGtRekQvRGZFc2RPVUx0Q2ZrRml0MDAKLS0tIGpyeG5mbmJkZW9QQ2lhSzA3YWNV
            TENrM3lHVG5CdGY0Nm11TTk5cFE0RzQK1HT7bUPMORYFO0uUl+aP9ibGMwHEGPVI
            OmKrXm0Tt++LJXMW/dHv+Qpjlv9gO7PuTuVDAoC18Fd9W/BX/+jSPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T09:02:28Z"
    mac: ENC[AES256_GCM,data:NVWigRwDmDcfCMQLNCLLP4LUCh4GCFT8KFowzdjqXoIy1glTboBFvrBb/KdL56svxkekqNw1bgXbC5TMY6mA4mB7zDDS4xwEzEWaGVoCIG7WHQX4Uhx1qOF+wah2KYPLOEm6e17a0kSVDaLYRDofum8/S0rzVW18VloB9WNnewY=,iv:tAbnwJZogOm0rPSKlobTMQIPGB/91UetOMphpM5yIzM=,tag:4SzKTHKzktkbhHjDyjtaEg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:t5Mm1uE=,iv:V3hygYFvvRHk/SGjVuHHlhaYlV6hJUpk+suGY2GQ368=,tag:HwShWmBHlvrqGFTPtj4IKw==,type:str]
    password: ENC[AES256_GCM,data:nSbj/dWopETgwJHtmTHe0cr8REVw8HRINtQah2fF,iv:mx8n+5HtB44XeOKBdKi/66FPT5xPuqPL7NoGL349EEE=,tag:3nBdi2AxYWUxQiGyWBJBBw==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeW9UWW51YThuWWRHRTVs
            ZXF4WDl4YTdvT1crNW15K3U0ZWRqOUNITUZnCjVlQ21ETVpLeFp0SmhSSHMrL1Zl
            eGtRekQvRGZFc2RPVUx0Q2ZrRml0MDAKLS0tIGpyeG5mbmJkZW9QQ2lhSzA3YWNV
            TENrM3lHVG5CdGY0Nm11TTk5cFE0RzQK1HT7bUPMORYFO0uUl+aP9ibGMwHEGPVI
            OmKrXm0Tt++LJXMW/dHv+Qpjlv9gO7PuTuVDAoC18Fd9W/BX/+jSPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T09:02:28Z"
    mac: ENC[AES256_GCM,data:NVWigRwDmDcfCMQLNCLLP4LUCh4GCFT8KFowzdjqXoIy1glTboBFvrBb/KdL56svxkekqNw1bgXbC5TMY6mA4mB7zDDS4xwEzEWaGVoCIG7WHQX4Uhx1qOF+wah2KYPLOEm6e17a0kSVDaLYRDofum8/S0rzVW18VloB9WNnewY=,iv:tAbnwJZogOm0rPSKlobTMQIPGB/91UetOMphpM5yIzM=,tag:4SzKTHKzktkbhHjDyjtaEg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.10.2
