apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db
    namespace: nextcloud
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:pGRZj3rvTna+,iv:RNyYeXfIQq4LUNL1dcWBjL3ZBovZTcWNOff/WZ4Cyjs=,tag:I0GPKnxOx2v0fAlfjwOStg==,type:str]
    username: ENC[AES256_GCM,data:v+omKA/+3WNE,iv:dRLdc+hm9D4IWqqVzxMvDAlabcXTdD/Ru2op4q0V15c=,tag:FW/WMa7sQ/BiiAzjz6GM/w==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:LI3KRAJlkmHFJw8GGVgVH064KeZySZ2/7beqm4Ab,iv:JBo65bWCsFeUk35KJ1BazZAexlpFhXxJdoyK40yPeA8=,tag:8pt6kByXK+BtqD5z0XnT8Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:s4SjsvMV/T4GyEdluq5lNLijWSc/y+mPKtok6NF6,iv:3iwH4KahZhlPO3rwGjG+goD52iW/u9z8eljNnyeNsZ4=,tag:tEe1qi2M+aFdsT+OwpmzJQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:5CHrJ7E2GjXlbsvEFnGbL0cnb5ZZQZVswZsva5Cb,iv:JKtUdVwIjbVAUOrDiDyueRO+u0U7bWpGxfsR3gjULSI=,tag:Ea/y92J7vaHakTPttoanWQ==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVVg1eGxYMDRJeFBFMVV3
            V3R1RkdHck5WYVM0QitHVUllVUVKSVU4WWgwCjRFV1NFeGZtbm1iZU1IS2Q2UlB0
            aGdHUE5JcHhCR2d6YTNieFZIbm9ZcjQKLS0tIHZCMEd1UTVEc1ROTGIzczRjdlF4
            VktPM2IwTkhldVQzSVduRERha2J5Z0UKw13a59h6kCyO/xK5NKw2k2mBhNmfA1dy
            YLxGYBoAAmjsnlartgGeRUDishe4I9oMYtM4Btuz0f0YEXZNNTp7cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T10:52:52Z"
    mac: ENC[AES256_GCM,data:c7QAmZYEeLDooEK15jhlliMtl0qGPhC/XqDSJnVhu9syl/EINHaV9QJs12zDp3fGNGOCKnZt1AovaA/4zdzJC2+ZumcmEiCGtBN2rEKU21H4xFJQoAxBXz91Xe5vH0/LbPtt0xN9+A36qj9FyMa5QAIvrktmGQ5t1PZCG4hh5bw=,iv:LPyF6+2KHqf2yvxAPIL3b1MxOesZy9qbnjbW54b0xBo=,tag:7pWcmM5Oa/SaW/AmqODhwg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nVGpIEI=,iv:CbJn35AnTzHWgghS1xC/kDGemvMOUGEt+/rO3hTPBcw=,tag:k5A4pCVxjmuulj95WcDCug==,type:str]
    password: ENC[AES256_GCM,data:UjJtAx3896pVFKg93wkCTEpQta6iQ8Ff+nIm/q/+,iv:9EJOEoDOFbtxh5847Pk6tNSbL9KpTzL+s2lFNaefB/8=,tag:trdNJZ/nzQHzw2WO3klsPw==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVVg1eGxYMDRJeFBFMVV3
            V3R1RkdHck5WYVM0QitHVUllVUVKSVU4WWgwCjRFV1NFeGZtbm1iZU1IS2Q2UlB0
            aGdHUE5JcHhCR2d6YTNieFZIbm9ZcjQKLS0tIHZCMEd1UTVEc1ROTGIzczRjdlF4
            VktPM2IwTkhldVQzSVduRERha2J5Z0UKw13a59h6kCyO/xK5NKw2k2mBhNmfA1dy
            YLxGYBoAAmjsnlartgGeRUDishe4I9oMYtM4Btuz0f0YEXZNNTp7cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T10:52:52Z"
    mac: ENC[AES256_GCM,data:c7QAmZYEeLDooEK15jhlliMtl0qGPhC/XqDSJnVhu9syl/EINHaV9QJs12zDp3fGNGOCKnZt1AovaA/4zdzJC2+ZumcmEiCGtBN2rEKU21H4xFJQoAxBXz91Xe5vH0/LbPtt0xN9+A36qj9FyMa5QAIvrktmGQ5t1PZCG4hh5bw=,iv:LPyF6+2KHqf2yvxAPIL3b1MxOesZy9qbnjbW54b0xBo=,tag:7pWcmM5Oa/SaW/AmqODhwg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.10.2
