apiVersion: v1
kind: Namespace
metadata:
  name: nzbget
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:latest
          ports:
            - containerPort: 6789
          env:
            - name: PUID
              value: "911"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "Europe/Berlin"
            - name: NZBGET_USER
              valueFrom:
                secretKeyRef:
                  name: nzbget-secret
                  key: NZBGET_USER
            - name: NZBGET_PASS
              valueFrom:
                secretKeyRef:
                  name: nzbget-secret
                  key: NZBGET_PASS
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: downloads
          persistentVolumeClaim:
            claimName: nzbget-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: nzbget
spec:
  selector:
    app: nzbget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6789
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
  namespace: nzbget
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
spec:
  rules:
    - host: nzbget.luehr.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbget
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: nzbget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads
  namespace: nzbget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
