apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: samba
          image: ghcr.io/servercontainers/samba:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SETGID
                - SETUID  # wird oft auch benötigt
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: SAMBA_CONF_WORKGROUP
              value: HYRULE
            - name: SAMBA_CONF_SERVERSTRING
              value: samba.paperless
            - name: SAMBA_CONF_LOG_LEVEL
              value: "3"
            - name: SAMBA_LOGLEVEL
              value: "2"
            - name: AVAHI_DISABLE
              value: "true"
            - name: SAMBA_VOLUME_CONFIG_consume 
              value: "[consume]; path=/mnt/consume; valid users = paperless; guest ok = no; read only = no; browseable = yes"
            - name: SAMBA_VOLUME_CONFIG_export
              value: "[consume]; path=/mnt/export; valid users = paperless; guest ok = no; read only = yes; browseable = yes"
          envFrom:
            - secretRef:
                name: samba-user-secret
          ports:
            - containerPort: 445
          volumeMounts:
            - name: consume
              mountPath: /mnt/consume
            - name: export
              mountPath: /mnt/export
      volumes:
        - name: consume
          persistentVolumeClaim:
            claimName: paperless-paperless-ngx-consume
        - name: export
          persistentVolumeClaim:
            claimName: paperless-paperless-ngx-export
---
apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: paperless
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.178.212,fd00::212"
spec:
  type: LoadBalancer
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
  selector:
    app: samba
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
