apiVersion: v1
kind: Namespace
metadata:
    name: servarr
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: servarr
    namespace: servarr
spec:
    interval: 1h
    url: https://charts.kubito.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: servarr
    namespace: servarr
spec:
    chart:
        spec:
            chart: servarr
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: servarr
            version: 1.2.0
    interval: 1m0s
    timeout: 15m
    values:
      qbittorrent:
        enabled: false
      jellyfin:
        ingress:
          enabled: true
          hosts: ["jellyfin.luehr.dev"]
        nodeSelector:
          performance: fast
        persistence:
          config:
            storageClass: longhorn-retain
          media:
            enabled: true
            accessMode: ReadWriteMany
            existingClaim: servarr-jellyfin-media
          extraExistingClaimMounts:
            - name: servarr-jellyfin-downloads
              mountPath: /downloads
              readOnly: false
              existingClaim: servarr-jellyfin-downloads
      sonarr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: sonarr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
          additionalVolumes:
            - name: sonarr-downloads
              persistentVolumeClaim:
                claimName: servarr-jellyfin-downloads
          additionalMounts:
            - name: sonarr-downloads
              mountPath: /downloads
              readOnly: false
      prowlarr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: prowlarr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
      flaresolverr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: flaresolverr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
      jellyseerr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: jellyseerr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
      bazarr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: bazarr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
      radarr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: radarr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
          additionalVolumes:
            - name: radarr-downloads
              persistentVolumeClaim:
                claimName: servarr-jellyfin-downloads
          additionalMounts:
            - name: radarr-downloads
              mountPath: /downloads
              readOnly: false
      lidarr:
        ingress:
          enabled: true
          className: traefik-internal
          hosts:
            - host: lidarr.luehr.dev
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn-retain
          additionalVolumes:
            - name: lidarr-downloads
              persistentVolumeClaim:
                claimName: servarr-jellyfin-downloads
          additionalMounts:
            - name: lidarr-downloads
              mountPath: /downloads
              readOnly: false
