apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
  namespace: servarr
spec:
  storageClassName: teanau
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.239
    path: /media
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-media-nfs
  storageClassName: teanau
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-downloads-nfs
  namespace: servarr
spec:
  storageClassName: teanau
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.239
    path: /downloads
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-downloads
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: jellyfin-downloads-nfs
  storageClassName: teanau
