apiVersion: v1
kind: Secret
metadata:
    name: siyuan-secrets
    namespace: siyuan
type: Opaque
stringData:
    ACCESS_AUTH_CODE: ENC[AES256_GCM,data:BAq+Ybpzlxx0fvp2nir5IA==,iv:+U3KLZRASqU7v8QMVsdlUR2ZQ51fz6PjyYlw2kSj9E8=,tag:+K12PY8W18yZyHaHnOGZkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bURvTytlQ3dhNWQ1MURa
            RlUxeXJ0LzU5SXkvYUxMWFRBdlpuM1ZjK0hNCkxKYzI4L1R3ZWcrbnF2dThqZ3c0
            bkRNLzFTRDJMclhydlRIcmlCUU1La1kKLS0tIDVENm52Z1I4dVEycWNsa0FrbVdi
            N2xPZUNwR2JheHhvaG81bHRUem8rWHcKIsB3lQ9mC7/392RWXHRChv13N3u3dU5V
            P6NeVyRWiXxXlT+KVahsLEiFByjP5EeGeQwwdGdrhgrdXAePdTFo2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
    encrypted_regex: ^stringData$
    lastmodified: "2026-09-11T11:34:53Z"
    mac: ENC[AES256_GCM,data:qs8V4jnRtRZSNrgDKg/1PEqEFNdhkwIEdqdIqzM81/P0XcbviyxDBYdVJbaPySW5I+jSYl5A49g/E6gHHV9gMhQQ7soSWmUoVHqt/tI+VmBgKlx/AtsWZ7BmVwRjrz6ZEsk0py6csX7/qERi9EaXPyLOh1Ndizfq297lBJ3PdXc=,iv:nQvhE/P/ibJVxuhV49XaLiRr23GQ/MWL57FE2De3qNA=,tag:Gk0Z12Uj79+yBcxefydalg==,type:str]
    version: 3.13.3
