apiVersion: v1
kind: Secret
metadata:
    name: twenty-secrets
    namespace: twenty
type: Opaque
stringData:
    PG_DATABASE_PASSWORD: ENC[AES256_GCM,data:17Ke0IE7VI2/S4IF5efiLj7agPPVMsn7,iv:jVGGnS11c9ZiCXrt70L63BT7lnSXVMWr+k8sL9CW47A=,tag:EoAeEdzHtBeTaYRXsQjmNw==,type:str]
    PG_DATABASE_URL: ENC[AES256_GCM,data:/JQNtLEFld+y3J7OudW5ksfZHwyvS2uyJDDi18YvYu2Le2c6SyUjjgdYFwcz/+kYnMo9Wd2yf6pohdWu4yb8gWXQEPNofGVxhQ==,iv:wpnOTmXQGY4897tnUhGfCDYLgoOhTuBIgQiJOzIMQiU=,tag:aY4VjFsEjO25l0zcCeGoXg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:xsGMHKiKVFd4gP7jX/awc1Psxid9UTzm6KvdrmFRyUCWrmnOC1vahvzW2HA=,iv:T5MIbGsGoEK08RGnTB6peYhn28Pi+Mkd0Goo/o8qkEY=,tag:+U6tPxclvcLOBTwG2c7qlA==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:8Ajg35lN5SBqR6bVj3MRwEXk6JEJ9Qe3edY3ZP7DXYYs7CS5pC8kwJkhD5g=,iv:487qIXES0EYnzWffRIybti6b6K+9GWXkbHebS3rN9Eg=,tag:ixyfvrAdtAfABn/jSjRRLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjRPR2FaTis1YXM4L2Ir
            Q3FSYm5DZXhwYmF0cm9vSHZsNi92ZUMwZUF3CjIyWmJzaTlQZEcwc3Z3bG90OGd1
            YzRHamRWdWl4MUJwclcwU3dnd1U4TmcKLS0tIHVraU1aVVZ3VjZYS0M4TVQvOHNP
            K1BNSEtNdzdWa0o3Q2l2UFJHM29VYlEK5sNS0xE42ZEKWrL+cbQ328Z+3/uc1JWx
            qhE4BDDnrIpDZ4nm/zfb8ldQWlPicAghYV7zFIof0tFpwroR6XGjLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
    encrypted_regex: ^stringData$
    lastmodified: "2026-09-10T08:51:10Z"
    mac: ENC[AES256_GCM,data:6Z4Jlw+YrQosIlcJ+3mgu+58CMR3b2VO8mhQ4HpFcb8UIKyRCeKl5VPxyZEHQOkYP8ndBqphw6O3yIHDcOUSnZCkEozk0lBv/Ncfbh9my2Nfs1LPm0MKgj7lpaQAoNDQHB7CTf99p5b1yUiC6p/LuLLhx8QsoCljytEGFy77J34=,iv:KH7rgUeNlS9iPmqPq1JcMKHtYuiYzSAZTJKnLFBsuCw=,tag:ASHCo8Rml523UUoe08zM0g==,type:str]
    version: 3.13.3
