apiVersion: v1
kind: Namespace
metadata:
  name: unifi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 1h
  url: oci://ghcr.io/mkilchhofer/unifi-chart/unifi
  ref:
    semver: '>= 1.12.4'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  chartRef:
    kind: OCIRepository
    name: unifi
    namespace: unifi
  interval: 1m0s
  timeout: 5m
  values:
    replicaCount: 1
    timezone: Europe/Berlin
    persistence:
      enabled: true
      storageClass: longhorn
    unifiedService:
      enabled: false
    controllerService:
      enabled: false
    stunService:
      enabled: false
    discoveryService:
      enabled: false
    syslogService:
      enabled: false
    captivePortalService:
      ingress:
        enabled: true
        hosts:
          - unifi-captive.luehr.dev
    guiService:
      enabled: false
    speedtestService:
      enabled: false
    mongodb:
      enabled: false
    customCert:
      enabled: true
      isChain: true
      certName: unifi.crt
      keyName: unifi.key
      certSecret: "unifi-certificates"
    ingress:
      enabled: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: socat-unifi-relay
  namespace: unifi
spec:
  selector:
    matchLabels:
      app: socat-unifi-relay
  template:
    metadata:
      labels:
        app: socat-unifi-relay
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: socat
          image: alpine/socat:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 10001
              hostPort: 10001
              protocol: UDP
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "[+] Starting UDP4 relay..." &&
              socat -v UDP4-LISTEN:10001,fork UDP4:unifi.unifi.svc.hyrule.luehr.dev:10001 &

              echo "[+] Starting UDP6 relay..." &&
              socat -v UDP6-LISTEN:10001,fork UDP6:unifi.unifi.svc.hyrule.luehr.dev:10001 &

              wait -n
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.178.214,fd00::214"
spec:
  selector:
    app.kubernetes.io/name: unifi
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: inform
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: discover
      port: 10001
      targetPort: 10001
      protocol: UDP
    - name: speedtest
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
