apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-smb-driver
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/kubernetes-csi/csi-driver-smb.git
  ref:
    tag: v1.13.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-smb-driver
  namespace: flux-system
spec:
  interval: 6h
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-smb-driver
  path: ./deploy
  targetNamespace: kube-system
