---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole-repo
  namespace: pihole
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pihole-repo
      version: 2.31.0
  interval: 1m0s
  values:
    DNS1:
      192.168.178.1
    persistentVolumeClaim:
      enabled: true
      existingClaim: ""
      storageClassName: longhorn
      accessMode: ReadWriteOnce
      size: 500Mi
    dualStack:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - "pihole.luehr.dev"
      path: /
      pathType: ImplementationSpecific
    serviceWeb:
      loadBalancerIP: 192.168.178.211
      loadBalancerIPv6: fd00::211
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.178.211
      loadBalancerIPv6: fd00::211
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
      - 127.0.0.1
      - 8.8.8.8
    dnsmasq:
      customDnsEntries:
        - address=/unifi.luehr.dev/192.168.178.214
        - address=/unifi.luehr.dev/fd00::214
        - address=/mosquitto.luehr.dev/192.168.178.213
        - address=/mosquitto.luehr.dev/fd00::213
        - address=/pihole.luehr.dev/192.168.178.210
        - address=/pihole.luehr.dev/fd00::210
        - address=/nextcloud.luehr.dev/fd00::210
        - address=/nextcloud.luehr.dev/192.168.178.210
        - address=/paperless.luehr.dev/fd00::210
        - address=/paperless.luehr.dev/192.168.178.210
        - address=/homeassistant.luehr.dev/fd00::210
        - address=/homeassistant.luehr.dev/192.168.178.210
        - address=/ha-codeserver.luehr.dev/fd00::210
        - address=/ha-codeserver.luehr.dev/192.168.178.210
        - address=/samba.paperless.luehr.dev/fd00::212
        - address=/samba.paperless.luehr.dev/192.168.178.212
        - address=/bazarr.luehr.dev/fd00::210
        - address=/bazarr.luehr.dev/192.168.178.210
        - address=/flaresolverr.luehr.dev/fd00::210
        - address=/flaresolverr.luehr.dev/192.168.178.210
        - address=/jellyfin.luehr.dev/fd00::210
        - address=/jellyfin.luehr.dev/192.168.178.210
        - address=/jellyseerr.luehr.dev/fd00::210
        - address=/jellyseerr.luehr.dev/192.168.178.210
        - address=/lidarr.luehr.dev/fd00::210
        - address=/lidarr.luehr.dev/192.168.178.210
        - address=/prowlarr.luehr.dev/fd00::210
        - address=/prowlarr.luehr.dev/192.168.178.210
        - address=/radarr.luehr.dev/fd00::210
        - address=/radarr.luehr.dev/192.168.178.210
        - address=/readarr.luehr.dev/fd00::210
        - address=/readarr.luehr.dev/192.168.178.210
        - address=/sonarr.luehr.dev/fd00::210
        - address=/sonarr.luehr.dev/192.168.178.210
        - address=/nzbget.luehr.dev/fd00::210
        - address=/nzbget.luehr.dev/192.168.178.210
      customSettings:
        - interface=eth0
        - bind-interfaces
    admin:
      enabled: true
      existingSecret: pihole-secrets
      passwordKey: password
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pihole-web
#  namespace: pihole
#spec:
#  ipFamilyPolicy: RequireDualStack
#  ipFamilies:
#    - IPv4
#    - IPv6
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pihole-dns-tcp
#  namespace: pihole
#spec:
#  ipFamilyPolicy: RequireDualStack
#  ipFamilies:
#    - IPv4
#    - IPv6
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pihole-dns-udp
#  namespace: pihole
#spec:
#  ipFamilyPolicy: RequireDualStack
#  ipFamilies:
#    - IPv4
#    - IPv6
